### ISSUE TITLE
Invalid URI: Invalid port specified.

### ISSUE THREAD

**Issue by Baudin999** [KevReed/PlantUml.Net#19]
I'm using to following code to render a PlantUml diagram using the custom pico webserver:

```
var factory = new RendererFactory();
var settings = new PlantUmlSettings();
settings.RemoteUrl = "http://localhost:8001";
var renderer = factory.CreateRenderer(settings);

var bytes = renderer.Render(puml, OutputFormat.Svg);
return bytes;
```

I get the following error when running the above code:

```
Invalid URI: Invalid port specified.
```

The server is running, when I go to the address directly it works. Does anyone have a tip on how I can fix this?

**Comment by KevReed** [comment]
path is missing a trailing slash, updated to be more robust
