### ISSUE TITLE
Problem with special characters and UTF-8

### ISSUE THREAD

**Issue by R0Wi** [KevReed/PlantUml.Net#21]
Hi and thank's for this great library. I have a little problem while trying to render plantUml code containing special characters. I have following code:

```csharp
var renderer = new RendererFactory().CreateRenderer(new PlantUmlSettings { RemoteUrl = "http://www.plantuml.com/plantuml" });
var bytes = await renderer.RenderAsync("Alice --> Bob: Smörebrätü", OutputFormat.Png);
File.WriteAllBytes(@"out.png", bytes);
```

This is what i'd expect for 
`out.png`:
![out](https://user-images.githubusercontent.com/19730957/123598625-02457d80-d7f5-11eb-818c-026871f7c304.png)

but the Library gives me
![out_bug](https://user-images.githubusercontent.com/19730957/123598826-3ae55700-d7f5-11eb-81b0-356a99d349d5.png)

**Comment by KevReed** [comment]
fixed by #23
